import Header from '@/components/Header'
import Head from 'next/head'
import Hero from '../components/Hero';
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className="bg-deep-blue text-white h-screen snap-y snap-mandatory overflow-scroll z-0">
      <Head>
        <title>Aurelien Gremy</title>
        {/* <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container mx-auto'>
        {/* Header */}
        <Header/>
        {/* Hero */}
        <section id="hero" className="snap-center">
          <Hero />
        </section>
        {/* About */}
        {/* Experience */}
        {/* Skills */}
        {/* Projects */}
        {/* Contact Me */}

      </main>
    </div>
  )
}
